---
title: "Finding a running variable"
author: "Uni Lee"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
library(dplyr)
library(tidyr)
library(readxl)
library(janitor)
library(ggplot2)
library(ggpubr)
```

# Finding a running variable, control vs. treatment groups 

```{r}
# Load data 
# Source: Heeter, Jenny; O'Shaughnessy, Eric (2020): U.S. Voluntary Green Power Market Data 2019. National Renewable Energy Laboratory. https://data.nrel.gov/submissions/151

gp_2017 <- read_xlsx("Data/NREL_Green Power 2017 Data.xlsx", sheet=5, skip=2) 

gp_2019 <- read_xlsx("Data/NREL_Green_Power_Data_v2019.xlsx", sheet=4, skip=2) 

gp_2020 <- read_xlsx("Data/NREL_Green_Power_Data_v2020.xlsx", sheet=4, skip=2) 

# 2018 data doesn't have state-by-state data

# Wrangle
long_2017 <- gp_2017 %>% pivot_longer(cols=`Utility Green Pricing`:PPAs,
                         names_to = "Sourcing",
                         values_to = "MWh") %>%
  mutate(Year=2017) %>% select(State, Year, Sourcing, MWh)


long_2019 <- gp_2019 %>% pivot_longer(cols=`Utility Green Pricing`:PPAs,
                         names_to = "Sourcing",
                         values_to = "MWh") %>%
  mutate(Year=2019) %>% select(State, Year, Sourcing, MWh)

long_2020 <- gp_2020 %>% pivot_longer(cols=`Utility Green Pricing`:PPAs,
                         names_to = "Sourcing",
                         values_to = "MWh") %>%
  mutate(Year=2020) %>% select(State, Year, Sourcing, MWh)

gp_all <- full_join(full_join(long_2017, long_2019), long_2020)

nv_ca <- gp_all %>% filter(State %in% c("CA", "NV"))

ggplot(nv_ca, aes(x=factor(Year), y=MWh), fill="Sourcing") + geom_line() +
  facet_wrap(~State)

ppa <- gp_all %>% filter(Sourcing=="PPAs")

control_sub <- ppa %>% filter(Year == 2020 & MWh < 100)
control_states <- control_sub$State

`%!in%` <- Negate(`%in%`)
control <- ppa %>% filter(State %in% control_states)
treatment <- ppa %>% filter(State %!in% control_states)


ggplot(control, aes(x=factor(Year), y=MWh)) + geom_point() +
         facet_wrap(~State)
ggplot(treatment, aes(x=factor(Year), y=MWh)) + geom_point() +
         facet_wrap(~State)

ggplot(control, aes(x=factor(Year), y=MWh, fill=State)) + geom_bar(stat="identity", position="dodge") 

control_states <- unique(control$State)
treatment_states <- unique(control$State)

```
 
```{r}
net_capa_raw <- read.csv("Data/existcapacity_annual.csv", skip=1) %>% clean_names() # in MWh

net_capa_raw$nameplate_capacity_megawatts <- as.numeric(gsub(",","",net_capa_raw$nameplate_capacity_megawatts))

net_capa_tot <- net_capa_raw %>% filter(year>=2009, producer_type=="Total Electric Power Industry",
                                        fuel_source %in% c("Wind", "Solar Thermal and Photovoltaic", "Geothermal")) %>% 
  select(year, state_code, fuel_source, capacity = nameplate_capacity_megawatts) %>%
  group_by(year, state_code) %>%
  summarize(capacity=sum(capacity))
net_capa_tot
```

